#ifndef CLIENTMESSAGE_HPP
#define CLIENTMESSAGE_HPP

#   define ERROR "0 "

#   define RPL_WELCOME "001 "
#   define RPL_UMODEIS "221 "
#   define RPL_ADMINME "256 "
#   define RPL_ADMINLOC1 "257 "
#   define RPL_ADMINLOC2 "258 "
#   define RPL_ADMINEMAIL "259 "
#   define RPL_AWAY "301 "
#   define RPL_WHOISREGNICK "307 "
#   define RPL_WHOISUSER "311 "
#   define RPL_WHOISOPERATOR "313 "
#   define RPL_ENDOFWHO "315 "
#   define RPL_ENDOFWHOIS "318 "
#   define RPL_LISTSTART "321 "
#   define RPL_LIST "322 "
#   define RPL_LISTEND "323 "
#   define RPL_CHANNELMODEIS "324 "
#   define RPL_NOTOPIC "331 "
#   define RPL_TOPIC "332 "
#   define RPL_INVITING "341 "
#   define RPL_WHOREPLY "352 "
#   define RPL_NAMREPLY "353 "
#   define RPL_ENDOFNAMES "366 "
#   define RPL_WHOISHOST "378 "
#   define RPL_WHOISMODES "379 "
#   define RPL_YOUREOPER "381 "
#   define RPL_TIME "391 "
#   define ERR_NOSUCHNICK "401 "
#   define ERR_NOSUCHSERVER "402 "
#   define ERR_NOSUCHCHANNEL "403 "
#   define ERR_CANNOTSENDTOCHAN "404 "
#   define ERR_NOORIGIN "409 "
#   define ERR_NORECIPIENT "411 "
#   define ERR_NOTEXTTOSEND "412 "
#   define ERR_UNKNOWNCOMMAND "421 "
#   define ERR_NONICKNAMEGIVEN "431 "
#   define ERR_ERRONEUSNICKNAME "432 "
#   define ERR_NICKNAMEINUSE "433 "
#   define ERR_USERNOTINCHANNEL "441 "
#   define ERR_NOTONCHANNEL "442 "
#   define ERR_USERONCHANNEL "443 "
#   define ERR_NEEDMOREPARAMS "461 "
#   define ERR_PASSWDMISMATCH "464 "
#   define ERR_UNKNOWNMODE "472 "
#   define ERR_BADCHANMASK "476 "
#   define ERR_NOCHANMODES "477 "
#   define ERR_CHANOPRIVSNEEDED "482 "
#   define ERR_NOPRIVILEGES "723 "
#   define ERR_NOPRIVS "481 "
#   define ERR_UMODEUNKNOWNFLAG "501 "
#   define ERR_USERSDONTMATCH "502 "
#   define ERR_ALREADYREGISTRED "642 "

#endif