#ifndef CLIENTMESSAGE_HPP
#define CLIENTMESSAGE_HPP


#   define RPL_WELCOME "001 "
#   define ERR_NOSUCHNICK "401 "
#   define ERR_USERSDONTMATCH "502 "
#   define RPL_UMODEIS "221 "
#   define ERR_ALREADYREGISTRED "642 "
#   define ERR_PASSWDMISMATCH "464 "
#   define ERR_NICKNAMEINUSE "433 "
#   define ERR_ERRONEUSNICKNAME "432 "
#   define ERROR "0"
#   define ERR_NEEDMOREPARAMS "461 "




#endif